### PR TITLE
Update deploy links and labels to Vertex AI Workbench

### PR DESCRIPTION
**Pull request by prodonjs**
Cloud AI Platform Notebooks is now branded as Vertex AI Workbench (https://cloud.google.com/vertex-ai/docs/workbench/introduction).

This updates all links to the proper format and branding.

### CODE REVIEW

**Comment by prodonjs** [comment]
@GoogleCloudPlatform/vertex-ai-samples-owners 

I'm trying to update the deployment links that are currently outdated for the Vertex AI Workbench (formerly Notebooks) product. Unfortunately it looks like I'm triggering a bunch of lint errors that were previously present in the submitted code that don't appear to be able to be fixed manually.

I can certainly take a stab at addressing them but there are quite a few files here and I was wondering if there was a manual override possible in this case since my change is a strict find/replace. Thanks!

**Comment by ivanmkc** [comment]
This will be a tough PR to fix. Partially as it's a bit old and will require some rebasing.

I recommend:
1. Removing any changes to non-notebook files like the changes to the linter infra.
2. Updating local main
3. Rebasing on local main
4. Push
5. See what notebooks have conflicts and remove them from this PR for now.

**Comment by kweinmeister** [comment]
@prodonjs Do you want to still proceed with this PR, or should we close it?

**Comment by prodonjs** [comment]
@kweinmeister - I would like to try to get this in purely to find/replace the broken links.

**Comment by andrewferlitsch** [comment]
Google Cloud Build / vertex-ai-notebook-execution-test (python-docs-samples-tests)
failed 6 days ago in 7h 24m 23s

**Comment by ivanmkc** [comment]
We will have to revisit this. It touches too many notebooks that there will inevitably be many conflicts.

**Pull request closed without merging**
