### PR TITLE
Add new notebook to community folder for BQML inference engine / Vertex AI API integration

### PR DESCRIPTION
**Pull request by rachael-ds**
<br>
Add new notebook to community folder for BQML inference engine / Vertex AI API integration. This will accompany a blog that is to be published next week.
<br><br><br>

<br>

2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
- [ Y ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the `Community Notebooks` section, pointing to the author or the author's team.
- [ Y ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

### CODE REVIEW

**Comment by rachael-ds** [comment]
<p>updated, ta</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675389'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rachael-ds** [comment]
<p>updated, ta</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675415'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rachael-ds** [comment]
<p>updated, ta</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675437'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rachael-ds** [comment]
<p>updated, ta</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675470'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rachael-ds** [comment]
<p>apologies, this should be resolved across the notebook now</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675489'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rachael-ds** [comment]
<p>updated, ta</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675513'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rachael-ds** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675556'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rachael-ds** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675601'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by rachael-ds** [comment]
<p>updated, thanks</p>

---

 <a href='https://app.reviewnb.com/GoogleCloudPlatform/vertex-ai-samples/pull/1820/discussion/#comment-1538675634'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by andrewferlitsch — APPROVED** [review]

**Pull request merged**
