### PR TITLE
Adding the official version for SDK-FB-prophet-online-forecasting-notebook

### PR DESCRIPTION
**Pull request by krishr2d2**
Checklist for moving the notebook to the main repo: 
- [x] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [x] Follow the style and grammar rules outlined in the above notebook template.
- [x] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [x] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [x] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under `# Official Notebooks` section, pointing to the author or the author's team.
- [x] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

### CODE REVIEW

**Comment by kweinmeister** [comment]
I saw a failure installing `pystan` in the build logs.

**Comment by krishr2d2** [comment]
> I saw a failure installing `pystan` in the build logs.

It must be the build related error messages while installing the fbprophet library. Those messages while installation seem common while installing fbprophet according to : https://github.com/facebook/prophet/issues/1598 but ultimately the library gets installed.

**Comment by ivanmkc** [comment]
@sudarshan-SpringML Please fix PR title. It's not clear if it's a small edit or a whole new notebook from the title.

**Comment by krishr2d2** [comment]
> @krishr2d2 The installation seemed to never finish after 17 hours. This is one of those cases where you'll have to dig a bit into why pip is behaving this way.
> 
> I recommend using Vertex Workbench with a custom container to debug: Screen Shot 2022-02-28 at 11 35 54 AM
> 
> The image you should use is gcr.io/cloud-devrel-public-resources/python-samples-testing-docker:latest

@ivanmkc Are there any additional steps to get the instance started?? I tried creating the instance using the provided image but it doesn't allow me to start it. 
no_jupyter_link
The "OPEN JUPYTERLAB" button gets greyed out.
Alternatively, I've tested separating out the steps that install the fb-propphet's dependencies and the fb-prophet library without any installation errors but unable to run the linter test successfully on the changes. The linter test gave the following two errors : 
```
error-1 : ImportError: cannot import name 'ParameterSource' from 'click.core' 

error-2 : ModuleNotFoundError: No module named 'absl'
```
These seem like coming from the linter test script rather than the the notebook.

**Comment by krishr2d2** [comment]
> > @krishr2d2 The installation seemed to never finish after 17 hours. This is one of those cases where you'll have to dig a bit into why pip is behaving this way.
> > I recommend using Vertex Workbench with a custom container to debug: Screen Shot 2022-02-28 at 11 35 54 AM
> > The image you should use is gcr.io/cloud-devrel-public-resources/python-samples-testing-docker:latest
> 
> @ivanmkc Are there any additional steps to get the instance started?? I tried creating the instance using the provided image but it doesn't allow me to access the JupyterLab on it. no_jupyter_link The "OPEN JUPYTERLAB" button gets greyed out.
> 
> Alternatively, I've tested separating out the steps that install the fb-propphet's dependencies and the fb-prophet library without any installation errors on the user-managed instances but unable to run the linter test successfully on the changes. The linter test gave the following two errors :
> 
> ```
> error-1 : ImportError: cannot import name 'ParameterSource' from 'click.core' 
> 
> error-2 : ModuleNotFoundError: No module named 'absl'
> ```
> 
> These seem like coming from the linter test script rather than the the notebook.

The linter test related errors are gone after re-installing the requirements for linter test.

**Comment by krishr2d2** [comment]
@kweinmeister , please run /gcbrun now to test it.

**Comment by kweinmeister** [comment]
Build failed due to "Failed to build pystan"

**Comment by kweinmeister** [comment]
The build goes further now, but pystan compilation fails with `gcc: fatal error: Killed signal terminated program cc1plus`, which could be an out-of-memory error. FYI @ivanmkc

**Comment by krishr2d2** [comment]
> @krishr2d2 test error:
> 
> Step #3: papermill.exceptions.PapermillExecutionError: Step #3: --------------------------------------------------------------------------- Step #3: Exception encountered at "In [17]": Step #3: --------------------------------------------------------------------------- Step #3: ModuleNotFoundError Traceback (most recent call last) Step #3: Input In [17], in <cell line: 6>() Step #3: 4 # BQ libraries Step #3: 5 import google.auth Step #3: ----> 6 from fbprophet import Prophet Step #3: 7 from google.cloud import bigquery Step #3: 9 TODAY = datetime.date.today() Step #3: Step #3: ModuleNotFoundError: No module named 'fbprophet' Step #3: Finished Step #3

These logs suggest that fbprophet was not installed properly. I don't understand why it is so. When I tested it in the testing environment[python-samples-testing-docker:latest], fbprophet got imported successfully as shown below.  
fbp_install_test_instance

**Comment by ivanmkc** [comment]
Sharing the executed ipynb file (see build logs for the GCS URI), can help debug.

**Comment by andrewferlitsch** [comment]
From the test output, looks like there is an install dependency on "pystan":

[1;35mnote[0m: This error originates from a subprocess, and is likely not a problem with pip.
Step #3: INFO:papermill:[1;31merror[0m: [1mlegacy-install-failure[0m
Step #3: 
Step #3: [31mÃ—[0m Encountered error while trying to install package.
Step #3: [31mâ•°â”€>[0m pystan
Step #3: 
Step #3: [1;35mnote[0m: This is an issue with the package mentioned above, not pip.
Step #3: [1;36mhint[0m: See above for output from the failure.
Step #3: 
Step #3: [1;31merror[0m: [1mlegacy-install-failure[0m
Step #3: 
Step #3: [31mÃ—[0m Encountered error while trying to install package.
Step #3: [31mâ•°â”€>[0m pystan
Step #3: 
Step #3: [1;35mnote[0m: This is an issue with the package mentioned above, not pip.
Step #3: [1;36mhint[0m: See above for output from the failure.
Step #3: INFO:papermill:Note: you may need to restart the kernel to use updated packages.
Step #3: 
Step #3: Note: you may need to restart the kernel to use updated packages.
Step #3: INFO:papermill:  [1;31merror[0m: [1msubprocess-exited-with-error[0m
Step #3:   
Step #3:   [31mÃ—[0m [32mRunning setup.py install for fbprophet[0m did not run successfully.
Step #3:   [31mâ”‚[0m exit code: [1;36m1[0m
Step #3:   [31mâ•°â”€>[0m [31m[42 lines of output][0m
Step #3:   [31m   [0m running install
Step #3:   [31m   [0m running build
Step #3:   [31m   [0m running build_py
Step #3:   [31m   [0m creating build
Step #3:   [31m   [0m creating build/lib
Step #3:   [31m   [0m creating build/lib/fbprophet
Step #3:   [31m   [0m creating build/lib/fbprophet/stan_model
Step #3:   [31m   [0m Importing plotly failed. Interactive plots will not work.
Step #3:   [31m   [0m Traceback (most recent call last):
Step #3: 
Step #3:   [1;31merror[0m: [1msubprocess-exited-with-error[0m
Step #3:   
Step #3:   [31mÃ—[0m [32mRunning setup.py install for fbprophet[0m did not run successfully.
Step #3:   [31mâ”‚[0m exit code: [1;36m1[0m
Step #3:   [31mâ•°â”€>[0m [31m[42 lines of output][0m
Step #3:   [31m   [0m running install
Step #3:   [31m   [0m running build
Step #3:   [31m   [0m running build_py
Step #3:   [31m   [0m creating build
Step #3:   [31m   [0m creating build/lib
Step #3:   [31m   [0m creating build/lib/fbprophet
Step #3:   [31m   [0m creating build/lib/fbprophet/stan_model
Step #3:   [31m   [0m Importing plotly failed. Interactive plots will not work.
Step #3:   [31m   [0m Traceback (most recent call last):
Step #3: INFO:papermill:  [31m   [0m   File "<string>", line 2, in <module>
Step #3:   [31m   [0m   File "<pip-setuptools-caller>", line 34, in <module>
Step #3:   [31m   [0m   File "/tmp/pip-install-uoawo_sr/fbprophet_dbe4f1b787ec458885087bc7e0fe86e3/setup.py", line 120, in <module>
Step #3:   [31m   [0m     setup(
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
Step #3:   [31m   [0m     return distutils.core.setup(**attrs)
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
Step #3:   [31m   [0m     dist.run_commands()
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
Step #3:   [31m   [0m     self.run_command(cmd)
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
Step #3:   [31m   [0m     cmd_obj.run()
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
Step #3:   [31m   [0m     return orig.install.run(self)
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/command/install.py", line 546, in run
Step #3:   [31m   [0m     self.run_command('build')
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
Step #3:   [31m   [0m     self.distribution.run_command(command)
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
Step #3:   [31m   [0m     cmd_obj.run()
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/command/build.py", line 135, in run
Step #3:   [31m   [0m     self.run_command(cmd_name)
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/cmd.py", line 313, in run_command
Step #3:   [31m   [0m     self.distribution.run_command(command)
Step #3:   [31m   [0m   File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
Step #3:   [31m   [0m     cmd_obj.run()
Step #3:   [31m   [0m   File "/tmp/pip-install-uoawo_sr/fbprophet_dbe4f1b787ec458885087bc7e0fe86e3/setup.py", line 48, in run
Step #3:   [31m   [0m     build_models(target_dir)
Step #3:   [31m   [0m   File "/tmp/pip-install-uoawo_sr/fbprophet_dbe4f1b787ec458885087bc7e0fe86e3/setup.py", line 38, in build_models
Step #3:   [31m   [0m     StanBackendEnum.get_backend_class(backend).build_model(target_dir, MODEL_DIR)
Step #3:   [31m   [0m   File "/tmp/pip-install-uoawo_sr/fbprophet_dbe4f1b787ec458885087bc7e0fe86e3/fbprophet/models.py", line 206, in build_model
Step #3:   [31m   [0m     import pystan
Step #3:   [31m   [0m ModuleNotFoundError: No module named 'pystan'
Step #3:   [31m   [0m [31m[end of output][0m
Step #3:

**Comment by andrewferlitsch** [comment]
Test log:
Finished Step #3
Starting Step #4
Step #4: Already have image (with digest): gcr.io/cloud-devrel-public-resources/python-samples-testing-docker:latest
Step #4: Requirement already satisfied: pip in /usr/local/lib/python3.9/site-packages (21.0.1)
Step #4: Collecting pip
Step #4:   Using cached pip-22.0.4-py3-none-any.whl (2.1 MB)
Step #4: Installing collected packages: pip
Step #4:   Attempting uninstall: pip
Step #4:     Found existing installation: pip 21.0.1
Step #4:     Uninstalling pip-21.0.1:
Step #4:       Successfully uninstalled pip-21.0.1
Step #4: Successfully installed pip-22.0.4
Step #4: ansiwrap==0.8.4
Step #4: appdirs==1.4.4
Step #4: argon2-cffi==21.3.0
Step #4: argon2-cffi-bindings==21.2.0
Step #4: asttokens==2.0.5
Step #4: attrs==21.4.0
Step #4: backcall==0.2.0
Step #4: beautifulsoup4==4.11.1
Step #4: bleach==5.0.0
Step #4: cachetools==5.0.0
Step #4: certifi==2021.10.8
Step #4: cffi==1.15.0
Step #4: charset-normalizer==2.0.12
Step #4: click==8.1.2
Step #4: cycler==0.11.0
Step #4: debugpy==1.6.0
Step #4: decorator==5.1.1
Step #4: defusedxml==0.7.1
Step #4: distlib==0.3.1
Step #4: entrypoints==0.4
Step #4: executing==0.8.3
Step #4: fastjsonschema==2.15.3
Step #4: filelock==3.0.12
Step #4: fonttools==4.33.1
Step #4: gcloud==0.18.3
Step #4: google-api-core==2.7.2
Step #4: google-auth==2.6.6
Step #4: google-cloud-aiplatform==1.12.1
Step #4: google-cloud-bigquery==2.34.3
Step #4: google-cloud-build==3.8.1
Step #4: google-cloud-core==2.3.0
Step #4: google-cloud-resource-manager==1.4.1
Step #4: google-cloud-storage==2.3.0
Step #4: google-crc32c==1.3.0
Step #4: google-resumable-media==2.3.2
Step #4: googleapis-common-protos==1.56.0
Step #4: grpc-google-iam-v1==0.12.4
Step #4: grpcio==1.44.0
Step #4: grpcio-status==1.44.0
Step #4: httplib2==0.20.4
Step #4: idna==3.3
Step #4: ipykernel==6.13.0
Step #4: ipython==8.2.0
Step #4: ipython-genutils==0.2.0
Step #4: ipywidgets==7.7.0
Step #4: jedi==0.18.1
Step #4: Jinja2==3.1.1
Step #4: jsonschema==4.4.0
Step #4: jupyter==1.0.0
Step #4: jupyter-client==7.2.2
Step #4: jupyter-console==6.4.3
Step #4: jupyter-core==4.10.0
Step #4: jupyterlab-pygments==0.2.2
Step #4: jupyterlab-widgets==1.1.0
Step #4: kiwisolver==1.4.2
Step #4: MarkupSafe==2.1.1
Step #4: matplotlib==3.5.1
Step #4: matplotlib-inline==0.1.3
Step #4: mistune==0.8.4
Step #4: nbclient==0.6.0
Step #4: nbconvert==6.5.0
Step #4: nbformat==5.3.0
Step #4: nest-asyncio==1.5.5
Step #4: notebook==6.4.11
Step #4: numpy==1.22.3
Step #4: oauth2client==4.1.3
Step #4: packaging==21.3
Step #4: pandas==1.4.2
Step #4: pandocfilters==1.5.0
Step #4: papermill==2.3.4
Step #4: parso==0.8.3
Step #4: pexpect==4.8.0
Step #4: pickleshare==0.7.5
Step #4: Pillow==9.1.0
Step #4: prometheus-client==0.14.1
Step #4: prompt-toolkit==3.0.29
Step #4: proto-plus==1.20.3
Step #4: protobuf==3.20.1
Step #4: psutil==5.9.0
Step #4: ptyprocess==0.7.0
Step #4: pure-eval==0.2.2
Step #4: pyasn1==0.4.8
Step #4: pyasn1-modules==0.2.8
Step #4: pycparser==2.21
Step #4: Pygments==2.11.2
Step #4: pyparsing==3.0.8
Step #4: pyrsistent==0.18.1
Step #4: python-dateutil==2.8.2
Step #4: pytz==2022.1
Step #4: PyYAML==6.0
Step #4: pyzmq==22.3.0
Step #4: qtconsole==5.3.0
Step #4: QtPy==2.0.1
Step #4: requests==2.27.1
Step #4: rsa==4.8
Step #4: Send2Trash==1.8.0
Step #4: six==1.15.0
Step #4: soupsieve==2.3.2.post1
Step #4: stack-data==0.2.0
Step #4: tabulate==0.8.9
Step #4: tenacity==8.0.1
Step #4: terminado==0.13.3
Step #4: textwrap3==0.9.2
Step #4: tinycss2==1.1.1
Step #4: tornado==6.1
Step #4: tqdm==4.64.0
Step #4: traitlets==5.1.1
Step #4: urllib3==1.26.9
Step #4: virtualenv==20.4.3
Step #4: wcwidth==0.2.5
Step #4: webencodings==0.5.1
Step #4: widgetsnbextension==3.6.0
Step #4: Copying file://source_archived_87f443e3-f372-4564-8eb7-c87288b6e21d.tar.gz [Content-Type=application/x-tar]...
Step #4: / [0 files][    0.0 B/  7.4 MiB]                                                
/ [1 files][  7.4 MiB/  7.4 MiB]                                                
Step #4: Operation completed over 1 objects/7.4 MiB.                                      
TIMEOUT

**Comment by krishr2d2** [comment]
This(TIMEOUT) doesn't seem to happen when testing locally. I suspect this occurred at the docker image building step as that step is a little ambiguous. Sometimes it needed to be run again to run successfully when it failed. 

Other than that, is there any time limit or other constraints for docker image building process in the testing env?

**Comment by andrewferlitsch** [comment]
test running > 3days
Apparently Cloud build just fixed that bug in the latest release
Might have to gcbrun again to see the fix

**Comment by andrewferlitsch** [comment]
@ivanmkc gcbrun was 16 days ago, but still running?

**Comment by krishr2d2** [comment]
@ivanmkc , Is there a way to access the executed notebook for this PR. I can't find it currently as the logs are truncated. Also, the docker builds are replaced by gcloud build commands. Still, I suspect that the container building process is taking a lot of time in this case ultimately leading to a TIMEOUT.

**Review by andrewferlitsch — APPROVED** [review]

**Comment by andrewferlitsch** [comment]
ValueError                                Traceback (most recent call last)
Step #5: Step #4: Cell In [21], line 6
Step #5: Step #4:       1 get_ipython().run_line_magic('cd', 'app/')
Step #5: Step #4:       3 # Choose a few product categories to build forecasts for from the Iowa Liquor sales data in BQ: bigquery-public-data:iowa_liquor_sales.sales
Step #5: Step #4:       4 # 1012100 CANADIAN WHISKIES
Step #5: Step #4:       5 # 1031100 AMERICAN VODKAS
Step #5: Step #4: ----> 6 train("1012100")
Step #5: Step #4:       7 train("1031100")
Step #5: Step #4:       9 get_ipython().run_line_magic('cd', '..')
Step #5: Step #4: 
Step #5: Step #4: Cell In [20], line 30, in train(category)
Step #5: Step #4:      28 # Train the Prophet model
Step #5: Step #4:      29 model = Prophet()
Step #5: Step #4: ---> 30 model.fit(df_forecast)
Step #5: Step #4:      32 # Save the model locally
Step #5: Step #4:      33 joblib.dump(model, "{}.sav".format(category))
Step #5: Step #4: 
Step #5: Step #4: File /workspace/workspace/env/lib/python3.9/site-packages/prophet/forecaster.py:1113, in Prophet.fit(self, df, **kwargs)
Step #5: Step #4:    1111 history = df[df['y'].notnull()].copy()
Step #5: Step #4:    1112 if history.shape[0] < 2:
Step #5: Step #4: -> 1113     raise ValueError('Dataframe has less than 2 non-NaN rows.')
Step #5: Step #4:    1114 self.history_dates = pd.to_datetime(pd.Series(df['ds'].unique(), name='ds')).sort_values()
Step #5: Step #4:    1116 history = self.setup_dataframe(history, initialize_scales=True)
Step #5: Step #4: 
Step #5: Step #4: ValueError: Dataframe has less than 2 non-NaN rows.

**Pull request merged**
