### PR TITLE
Fixed End to End Run

### PR DESCRIPTION
**Pull request by willisc7**
<br>
Currently, the automl_image_object_detection_online_prediction.ipynb notebook creates a corrupted Dataset during the "Create the Dataset" step.  When you run the training pipeline it will say the Dataset is empty. I put in steps to copy all the files to the bucket the user creates in the beginning and use those instead of the ones in the public bucket.
<br><br><br>

**REQUIRED:** Fill out the below checklists or remove if irrelevant
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [x] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [x] Follow the style and grammar rules outlined in the above notebook template.
- [x] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [x] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
- [x] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [x] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/CODEOWNERS) file under the `Official Notebooks` section, pointing to the author or the author's team.
- [x] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

### CODE REVIEW

**Comment by felipeliliti** [comment]
Liberar agora

**Comment by gericdong** [comment]
@willisc7 can you please take a look at the linter errors? Thanks.
/gcbrun

**Comment by willisc7** [comment]
@gericdong should be good to go now!

**Comment by gericdong** [comment]
@willisc7: the test is failing https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/2968/checks?check_run_id=26942405590. Can you please check it out? Thanks.

**Comment by willisc7** [comment]
Is there a good way to see a better diff between my commit and the current code? For some reason the commit just shows the entire file being replaced. Also, is there a way we can just host a persistent dataset? If I recall correctly, the issue I was working around was that the GCS bucket in the existing tutorial doesn't have the proper permissions for the end-to-end run to work. We could fix this by just hosting the dataset in a public bucket in a dedicated project.

**Comment by gericdong** [comment]
I am closing this PR for now. Please reopen when the work resumes.

**Pull request closed without merging**
