### PR TITLE
Add co-hosting model notebook

### PR DESCRIPTION
**Pull request by xingziye**
If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [ ] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [ ] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [ ] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/CODEOWNERS) file under the `Official Notebooks` section, pointing to the author or the author's team.
- [ ] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the `Community Notebooks` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/community-content) folder:
- [ ] Make sure your main `Content Directory Name` is descriptive, informative, and includes some of the key products and attributes of your content, so that it is differentiable from other content
- [ ] The main content directory has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/CODEOWNERS) file under the `Community Content` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

### CODE REVIEW

**Comment by andrewferlitsch** [comment]
@ivanmkc test not ran: Changed files did not match file filter

**Review by andrewferlitsch — APPROVED** [review]

**Comment by andrewferlitsch** [comment]
Failure:
Step #5: FailedPrecondition: 400 Endpoint projects/1012616486416/locations/us-central1/endpoints/5556518350407860224 doesn't have traffic_split.
Step #5: 
Finished Step #5
ERROR
ERROR:

**Comment by ivanmkc** [comment]
Reaching out to author to see if they want to close the PR.

**Comment by ivanmkc** [comment]
@xingziye you should use the Python SDK instead of the REST API: https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform_v1beta1/services/deployment_resource_pool_service/async_client.py

**Comment by xingziye** [comment]
> @xingziye you should use the Python SDK instead of the REST API: https://github.com/googleapis/python-aiplatform/blob/main/google/cloud/aiplatform_v1beta1/services/deployment_resource_pool_service/async_client.py

The orignal community notebook was created when SDK was not available. Will follow up with the orignal author to update the notebook.

**Pull request merged**
