### PR TITLE
Add metadata to hide cells

### PR DESCRIPTION
**Pull request by nicain**

### CODE REVIEW

**Comment by nicain** [comment]
This PR is failing linting, because `python3 -m tensorflow_docs.tools.nbfmt AlphaFold.ipynb` is not happy with the metadata that hides the cells (the only changes in the commit). NBCompare has no issues, though, and I have tested that this notebook executes properly, so I think we should force-merge this PR. I have verified that Workbench can launch the notebook from the feature branch (https://console.cloud.google.com/vertex-ai/workbench/deploy-notebook?download_url=https://github.com/GoogleCloudPlatform/vertex-ai-samples/raw/alphafold_hide_cell/community-content/alphafold_on_workbench/AlphaFold.ipynb), that the cells on the launched notebook are hidden properly, and that the notebook executes without issue.

**Comment by ivanmkc** [comment]
Can you elaborate on "the metadata that hides the cells"? For official notebooks, we don't use those. Since this is community, I'll leave it to your judgement but don't recommend it.

**Comment by ivanmkc** [comment]
Let me take off the linting requirement so it unblocks you.

**Review by ivanmkc — APPROVED** [review]
LGTM

**Comment by ivanmkc** [comment]
Missing PR description explaining why this was needed and what was changed.

**Pull request merged**
