### PR TITLE
change the directory in pipeline parameter values

### PR DESCRIPTION
**Pull request by graciofilipe**
making consistent the parameter values with the directory of data download

If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [ ] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [ ] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [ ] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under `# Official Notebooks` section, pointing to the author or the author's team.
- [ ] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under the `# Community Notebooks` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).

If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/community-content) folder:
- [ ] Make sure your main `Content Directory Name` is descriptive, informative, and includes some of the key products and attributes of your content, so that it is differentiable from other content
- [ ] The main content directory has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under the `# Community Content` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).

### CODE REVIEW

**Comment by andrewferlitsch** [comment]
@graciofilipe You need to sign the CLA.

**Comment by graciofilipe** [comment]
> 

@andrewferlitsch thanks, I'm clearly missing something, 'cause I thought I've been through this to contribute to the data-science-on-gcp repo. I have internally checked that I have the CLA.... I'm clearly doing something wrong, but I don't know what.

**Comment by graciofilipe** [comment]
> @graciofilipe You need to sign the CLA.

I also have the google email into my github email list... so.. confused, sorry.

**Comment by andrewferlitsch** [comment]
@graciofilipe Most likely your git configuration is not using the same email address you used to sign the CLA
so you should either amend those commits, or submit a new one using the matching email address

**Comment by andrewferlitsch** [comment]
@graciofilipe Did you see my previous comment?

**Comment by kweinmeister** [comment]
Hi @graciofilipe will you be able to fill out the CLA? If not, we will need to close the PR. Thank you!

**Comment by andrewferlitsch** [comment]
per Karl's comment on lack of CLA signed.

**Pull request closed without merging**
