### PR TITLE
Made minor changes to training-multi-class-classification-model-for-ads-targeting-usecase file and moved file from community to official folder

### PR DESCRIPTION
**Pull request by sudarshan-SpringML**
Made minor changes to training-multi-class-classification-model-for-ads-targeting-usecase file and moved file from community to official folder
- [X] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [X] Follow the style and grammar rules outlined in the above notebook template.
- [X] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [X] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [X] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under `# Official Notebooks` section, pointing to the author or the author's team.
- [X] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

### CODE REVIEW

**Comment by sudarshan-SpringML** [comment]
Notebook ran fine in colab and workbench

**Comment by andrewferlitsch** [comment]
Did not execute tests:
Changed files did not match file filter

**Comment by sudarshan-SpringML** [comment]
> Did not execute tests: Changed files did not match file filte

> Did not execute tests: Changed files did not match file filter

Not sure @andrewferlitsch. All changed files are in official folder. I moved them from community to official. There are some images in changed files. Is it because of that?

**Comment by andrewferlitsch** [comment]
Step #4: 
Step #4: FileNotFoundError: [Errno 2] No such file or directory: '/builder/home/.local/lib/python3.9/site-packages/protobuf-3.20.1.dist-info/METADATA'
Step #4: 
Finished Step #4
ERROR

**Comment by sudarshan-SpringML** [comment]
for this file created a new branch

**Pull request closed without merging**
