### PR TITLE
Adds the updated matching_engine/matching_engine_with_indexes notebook to the official folder.

### PR DESCRIPTION
**Pull request by krishr2d2**
Opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder:
- [x] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [x] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [x] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [x] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under `# Official Notebooks` section, pointing to the author or the author's team.
- [x] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

### CODE REVIEW

**Comment by krishr2d2** [comment]
Please note that this notebook uses a custom VPC network and was instructed to run specifically on an instance created using that custom VPC network. Also, it is already mentioned in the notebook that it may not run on Colab.

**Comment by ivanmkc** [comment]
@krishr2d2 this notebook is out of date. In any case, the matching engine notebooks are out-of-scope for now as they require a VPC set up which the CI test doesn't support at the moment.

**Comment by ivanmkc** [comment]
You can close this PR.

**Comment by krishr2d2** [comment]
Closing this PR....

**Pull request closed without merging**
