### PR TITLE
upgrade: boilerplate reduction #1

### PR DESCRIPTION
**Pull request by andrewferlitsch**
**REQUIRED:** Add a summary of your PR here, typically including why the change is needed and what was changed. Include any design alternatives for discussion purposes.

<br>
-Apply boilerplate reduction
<br><br><br>

**REQUIRED:** Fill out the below checklists or remove if irrelevant
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [ ] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [ ] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [ ] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/CODEOWNERS) file under the `Official Notebooks` section, pointing to the author or the author's team.
- [ ] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

<br>

2. If you are opening a PR for `Community Notebooks` under the [notebooks/community](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/community) folder:
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/community/CODEOWNERS) file under the `Community Notebooks` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

<br>

3. If you are opening a PR for `Community Content` under the [community-content](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/community-content) folder:
- [ ] Make sure your main `Content Directory Name` is descriptive, informative, and includes some of the key products and attributes of your content, so that it is differentiable from other content
- [ ] The main content directory has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/community-content/CODEOWNERS) file under the `Community Content` section, pointing to the author or the author's team.
- [ ] Passes all the required formatting and linting checks. You can locally test with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).

### CODE REVIEW

**Comment by andrewferlitsch** [comment]
---> 11 bq_dataset = client.create_dataset(bq_dataset)
Step #5: Step #4:      12 print(f"Created bigquery dataset {arima_dataset_path} in {DATA_REGION}")
Step #5: Step #4:      14 # Make this the same region as the other dataset for easier comparisons.
Step #5: Step #4: 
Step #5: Step #4: File /workspace/workspace/env/lib/python3.9/site-packages/google/cloud/bigquery/client.py:632, in Client.create_dataset(self, dataset, exists_ok, retry, timeout)
Step #5: Step #4:     629 try:
Step #5: Step #4:     630     span_attributes = {"path": path}
Step #5: Step #4: --> 632     api_response = self._call_api(
Step #5: Step #4:     633         retry,
Step #5: Step #4:     634         span_name="BigQuery.createDataset",
Step #5: Step #4:     635         span_attributes=span_attributes,
Step #5: Step #4:     636         method="POST",
Step #5: Step #4:     637         path=path,
Step #5: Step #4:     638         data=data,
Step #5: Step #4:     639         timeout=timeout,
Step #5: Step #4:     640     )
Step #5: Step #4:     641     return Dataset.from_api_repr(api_response)
Step #5: Step #4:     642 except core_exceptions.Conflict:
Step #5: Step #4: 
Step #5: Step #4: File /workspace/workspace/env/lib/python3.9/site-packages/google/cloud/bigquery/client.py:782, in Client._call_api(self, retry, span_name, span_attributes, job_ref, headers, **kwargs)
Step #5: Step #4:     778 if span_name is not None:
Step #5: Step #4:     779     with create_span(
Step #5: Step #4:     780         name=span_name, attributes=span_attributes, client=self, job_ref=job_ref
Step #5: Step #4:     781     ):
Step #5: Step #4: --> 782         return call()
Step #5: Step #4:     784 return call()
Step #5: Step #4: 
Step #5: Step #4: File /workspace/workspace/env/lib/python3.9/site-packages/google/api_core/retry.py:349, in Retry.__call__.<locals>.retry_wrapped_func(*args, **kwargs)
Step #5: Step #4:     345 target = functools.partial(func, *args, **kwargs)
Step #5: Step #4:     346 sleep_generator = exponential_sleep_generator(
Step #5: Step #4:     347     self._initial, self._maximum, multiplier=self._multiplier
Step #5: Step #4:     348 )
Step #5: Step #4: --> 349 return retry_target(
Step #5: Step #4:     350     target,
Step #5: Step #4:     351     self._predicate,
Step #5: Step #4:     352     sleep_generator,
Step #5: Step #4:     353     self._timeout,
Step #5: Step #4:     354     on_error=on_error,
Step #5: Step #4:     355 )
Step #5: Step #4: 
Step #5: Step #4: File /workspace/workspace/env/lib/python3.9/site-packages/google/api_core/retry.py:191, in retry_target(target, predicate, sleep_generator, timeout, on_error, **kwargs)
Step #5: Step #4:     189 for sleep in sleep_generator:
Step #5: Step #4:     190     try:
Step #5: Step #4: --> 191         return target()
Step #5: Step #4:     193     # pylint: disable=broad-except
Step #5: Step #4:     194     # This function explicitly must deal with broad exceptions.
Step #5: Step #4:     195     except Exception as exc:
Step #5: Step #4: 
Step #5: Step #4: File /workspace/workspace/env/lib/python3.9/site-packages/google/cloud/_http/__init__.py:494, in JSONConnection.api_request(self, method, path, query_params, data, content_type, headers, api_base_url, api_version, expect_json, _target_object, timeout, extra_api_info)
Step #5: Step #4:     482 response = self._make_request(
Step #5: Step #4:     483     method=method,
Step #5: Step #4:     484     url=url,
Step #5: Step #4:    (...)
Step #5: Step #4:     490     extra_api_info=extra_api_info,
Step #5: Step #4:     491 )
Step #5: Step #4:     493 if not 200 <= response.status_code < 300:
Step #5: Step #4: --> 494     raise exceptions.from_http_response(response)
Step #5: Step #4:     496 if expect_json and response.content:
Step #5: Step #4:     497     return response.json()
Step #5: Step #4: 
Step #5: Step #4: Conflict: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/python-docs-samples-tests/datasets?prettyPrint=false: Already Exists: Dataset python-docs-samples-tests:forecasting_demo_arima
Step #5: Step #4:

**Review by gericdong — APPROVED** [review]

**Pull request merged**
