### PR TITLE
Adds the updated get_started_bq_datasets-notebook from ml_ops/stage1 to the official folder

### PR DESCRIPTION
**Pull request by krishr2d2**
Checklist for opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder:
- [x] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [x] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [x] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [x] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under `# Official Notebooks` section, pointing to the author or the author's team.
- [x] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

This PR adds the reviewed and updated **ml_ops/stage1/get_started_bq_datasets.ipynb** to the official folder and removes the old file from the community folder.

### CODE REVIEW

**Comment by kweinmeister** [comment]
This is failing due to a version conflict where `google-api-core` gets installed, then uninstalled with a different version later. A possible solution might be to reorder pip installs or combine some on different lines. The two packages that I'm aware of that have a dependency constraint of <2 on google-api-core are currently: `google-cloud-pipeline-components` and `kfp`.

**Comment by krishr2d2** [comment]
Closing this pr and opening a new pr for moving the updates to the community folder for mlops.

**Pull request closed without merging**
