### PR TITLE
Added colab , installed some packages, added some code based on standard template and made changes in cleanup section for the file inventory_prediction.ipynb

### PR DESCRIPTION
**Pull request by Tharun-SpringML**
Added colab , installed some packages, added some code based on standard template and made changes in cleanup section for the file inventory_prediction.ipynb

If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [x] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [x] Follow the style and grammar rules outlined in the above notebook template.
- [x] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [x] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).
- [x] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under `# Official Notebooks` section, pointing to the author or the author's team.
- [x] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

### CODE REVIEW

**Comment by andrewferlitsch** [comment]
test still running:
Google Cloud Build / vertex-ai-notebook-execution-test (python-docs-samples-tests)
Started 1d 5h 3m 7s ago

**Comment by kweinmeister** [comment]
Build error: `ValueError: The pyarrow library is not installed, please install pyarrow to use the to_arrow() function.`

**Comment by sudarshan-SpringML** [comment]
Please do gcb run

**Comment by sudarshan-SpringML** [comment]
ran fine in workbench and colab

**Comment by andrewferlitsch** [comment]
@ivanmkc test not ran: Changed files did not match file filter

**Review by andrewferlitsch — APPROVED** [review]

**Pull request merged**
