### PR TITLE
Sdk automl text entity extraction online

### PR DESCRIPTION
**Pull request by sudarshan-SpringML**
This PR contains notebook which demonstrates how to use the Vertex SDK to create text entity extraction models and do online prediction using a Google Cloud [AutoML](https://cloud.google.com/vertex-ai/docs/start/automl-users) model.
- [x] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [x] Follow the style and grammar rules outlined in the above notebook template.
- [x] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [x] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).
- [x] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [x] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under `# Official Notebooks` section, pointing to the author or the author's team.
- [x] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

### CODE REVIEW

**Comment by kweinmeister** [comment]
Error in build log:
```
      1 dataset = aiplatform.TextDataset.create(
      2     display_name="NCBI Biomedical" + "_" + TIMESTAMP,
      3     gcs_source=[IMPORT_FILE],
----> 4     import_schema_uri=aip.schema.dataset.ioformat.text.extraction,
      5 )
      7 print(dataset.resource_name)

NameError: name 'aip' is not defined
```

**Comment by sudarshan-SpringML** [comment]
Noted karl. Thank you

**Comment by sudarshan-SpringML** [comment]
> Error in build log:
> 
> ```
>       1 dataset = aiplatform.TextDataset.create(
>       2     display_name="NCBI Biomedical" + "_" + TIMESTAMP,
>       3     gcs_source=[IMPORT_FILE],
> ----> 4     import_schema_uri=aip.schema.dataset.ioformat.text.extraction,
>       5 )
>       7 print(dataset.resource_name)
> 
> NameError: name 'aip' is not defined
> ```

fixed issue

**Comment by sudarshan-SpringML** [comment]
Comments resolved. Notebook can be reviewed

**Review by andrewferlitsch — APPROVED** [review]

**Pull request merged**
