### PR TITLE
Adds notebook for multi-node-ddp-nccl-custom-container-training usecase in the official folder

### PR DESCRIPTION
**Pull request by krishr2d2**
**REQUIRED:** Add a summary of your PR here, typically including why the change is needed and what was changed. Include any design alternatives for discussion purposes.

<br>
This notebook is being submitted as a replacement for the existing [multi_node_ddp_nccl_vertex_training_with_custom_container](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/training/multi_node_ddp_nccl_vertex_training_with_custom_container.ipynb) notebook.

This notebook is an updated and cleaned-up version of a notebook for a similar use case from [here](https://github.com/brianchunkang/ai-samples/blob/master/pytorch_image_classification_torchrun_ddp_training_sdk/multi_node_torchrun_ddp_vertex_training_custom_container.ipynb). 
The updates performed include: 

- replacing the dataset(tinyimagenet) with the one(Vegetable images dataset) with a public-license.
- removing the CPU (gloo) training part as it was already covered in another existing notebook in the training folder.
- adding a final step to list the created trained-model's artifacts.
- textual descriptions and explanations provided wherever needed according to the notebook template.

**Note:** This notebook has a dependency on files from the folder `trainer-gpu` sub-folder included in this PR.

<br><br><br>

**REQUIRED:** Fill out the below checklists or remove if irrelevant
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [x] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [x] Follow the style and grammar rules outlined in the above notebook template.
- [x] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [x] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/CODEOWNERS) file under the `Official Notebooks` section, pointing to the author or the author's team.
- [x] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

<br>

### CODE REVIEW

**Comment by gericdong** [comment]
@krishr2d2 can you please check why the notebook was failing the vertex-ai-notebook-execution-test and address the issue if it's a notebook issue? Thanks.

**Comment by krishr2d2** [comment]
> @krishr2d2 can you please check why the notebook was failing the vertex-ai-notebook-execution-test and address the issue if it's a notebook issue? Thanks.

This notebook has a dependency with the scripts in the "trainer-gpu" folder. From the logs, it appears that only the notebook is being copied to the environment and being run without the trainer scripts.

**Comment by ivanmkc** [comment]
The CI runs the notebook from the root repo folder, not the folder where the notebook is.

Perhaps it should though. Let me see if that's possible.

**Comment by ivanmkc** [comment]
I fixed the issue where it can't find the files.

The training still fails. See this log for details: https://drive.google.com/file/d/1S9rI11yhGmiwdDd82G5KAYhhvO15yhPF/view?usp=sharing&resourcekey=0-d9kuiDbYvJyQGHvQDz2NlA

**Comment by krishr2d2** [comment]
> I fixed the issue where it can't find the files: See the changes I made to .cloud-build/execute_notebook_helper.py.
> 
> The training still fails. See this log for details: https://drive.google.com/file/d/1S9rI11yhGmiwdDd82G5KAYhhvO15yhPF/view?usp=sharing&resourcekey=0-d9kuiDbYvJyQGHvQDz2NlA

The issue seems to be fixed now. The distributed training ran fine after I updated the replica count.

**Comment by andrewferlitsch** [comment]
This notebook is already covered in official. Obsolete

**Pull request closed without merging**
