### PR TITLE
update featurestore api version

### PR DESCRIPTION
**Pull request by haomengchao**
**REQUIRED:** Add a summary of your PR here, typically including why the change is needed and what was changed. Include any design alternatives for discussion purposes.

<br>
Update api version for featurestore.
And update a parameter's name as the old one is deprecated.
<br><br><br>

**REQUIRED:** Fill out the below checklists or remove if irrelevant
1. If you are opening a PR for `Official Notebooks` under the [notebooks/official](https://github.com/GoogleCloudPlatform/vertex-ai-samples/tree/main/notebooks/official) folder, follow this mandatory checklist:
- [ ] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [ ] Follow the style and grammar rules outlined in the above notebook template.
- [ ] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [ ] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/CONTRIBUTING.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/CODEOWNERS) file under the `Official Notebooks` section, pointing to the author or the author's team.
- [ ] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

<br>

### CODE REVIEW

**Comment by andrewferlitsch** [comment]
This GAPIC notebook is obsoleted by SDK version: https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/official/feature_store/sdk-feature-store.ipynb

Either delete or more to community

**Comment by ivanmkc** [comment]
@haomengchao It seems this notebook is broken because it doesn't use a UUID to set the feature store paths, leading to conflicts.

See the UUID section in https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb on how to create one.

**Comment by ivanmkc** [comment]
You should be able to fix it with:


```
FEATURESTORE_ID = f"movie_prediction_{uuid}"
```

**Review by ivanmkc — DISMISSED** [review]
Thanks for the update. Left some comments

**Review by andrewferlitsch — APPROVED** [review]

**Pull request merged**
