### PR TITLE
Refresh of PyTorch Image Classification Multi-Node Distributed Data Parallel Training on GPU using Vertex Training with Custom Container

### PR DESCRIPTION
**Pull request by manuelamunategui**
This PR contains a notebook that demonstrates how to create a multi-node, distributed image classification using PyTorch on Vertex SDK with GPU. This can help your training job scale to handle large amounts of data.

- [*] Use the [notebook template](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/notebooks/notebook_template.ipynb) as a starting point.
- [*] Follow the style and grammar rules outlined in the above notebook template.
- [*] Verify the notebook runs successfully in Colab since the automated tests cannot guarantee this even when it passes.
- [*] Passes all the required automated checks. You can locally test for formatting and linting with these [instructions](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/contributing.md#code-quality-checks).
- [ ] You have consulted with a tech writer to see if tech writer review is necessary. If so, the notebook has been reviewed by a tech writer, and they have approved it.
- [ ] This notebook has been added to the [CODEOWNERS](https://github.com/GoogleCloudPlatform/vertex-ai-samples/blob/main/docs/CODEOWNERS) file under `# Official Notebooks` section, pointing to the author or the author's team.
- [*] The Jupyter notebook cleans up any artifacts it has created (datasets, ML models, endpoints, etc) so as not to eat up unnecessary resources.

### CODE REVIEW

**Comment by manuelamunategui** [comment]
Works on workbench and Colab

**Comment by andrewferlitsch** [comment]
3: InvalidArgument                           Traceback (most recent call last)
Step #3: Input In [22], in <cell line: 1>()
Step #3: ----> 1 custom_container_training_job.run(
Step #3:       2     args=args,
Step #3:       3     base_output_dir=gcs_output_uri_prefix,
Step #3:       4     replica_count=replica_count,
Step #3:       5     machine_type=machine_type,
Step #3:       6     accelerator_count=accelerator_count,
Step #3:       7     accelerator_type=accelerator_type,
Step #3:       8     tensorboard=tensorboard.resource_name,
Step #3:       9     service_account=SERVICE_ACCOUNT,
Step #3:      10 )
Step #3: 
Step #3: File ~/.local/lib/python3.9/site-packages/google/cloud/aiplatform/training_jobs.py:2944, in CustomContainerTrainingJob.run(self, dataset, annotation_schema_uri, model_display_name, model_labels, base_output_dir, service_account, network, bigquery_destination, args, environment_variables, replica_count, machine_type, accelerator_type, accelerator_count, boot_disk_type, boot_disk_size_gb, reduction_server_replica_count, reduction_server_machine_type, reduction_server_container_uri, training_fraction_split, validation_fraction_split, test_fraction_split, training_filter_split, validation_filter_split, test_filter_split, predefined_split_column_name, timestamp_split_column_name, timeout, restart_job_on_worker_restart, enable_web_access, tensorboard, sync, create_request_timeout)
Step #3:    2680 """Runs the custom training job.
Step #3:    2681 
Step #3:    2682 Distributed Training Support:
Step #3:    (...)
Step #3:    2929         were not provided in constructor.
Step #3:    2930 """
Step #3:    2931 worker_pool_specs, managed_model = self._prepare_and_validate_run(
Step #3:    2932     model_display_name=model_display_name,
Step #3:    2933     model_labels=model_labels,
Step #3:    (...)
Step #3:    2941     reduction_server_machine_type=reduction_server_machine_type,
Step #3:    2942 )
Step #3: -> 2944 return self._run(
Step #3:    2945     dataset=dataset,
Step #3:    2946     annotation_schema_uri=annotation_schema_uri,
Step #3:    2947     worker_pool_specs=worker_pool_specs,
Step #3:    2948     managed_model=managed_model,
Step #3:    2949     args=args,
Step #3:    2950     environment_variables=environment_variables,
Step #3:    2951     base_output_dir=base_output_dir,
Step #3:    2952     service_account=service_account,
Step #3:    2953     network=network,
Step #3:    2954     bigquery_destination=bigquery_destination,
Step #3:    2955     training_fraction_split=training_fraction_split,
Step #3:    2956     validation_fraction_split=validation_fraction_split,
Step #3:    2957     test_fraction_split=test_fraction_split,
Step #3:    2958     training_filter_split=training_filter_split,
Step #3:    2959     validation_filter_split=validation_filter_split,
Step #3:    2960     test_filter_split=test_filter_split,
Step #3:    2961     predefined_split_column_name=predefined_split_column_name,
Step #3:    2962     timestamp_split_column_name=timestamp_split_column_name,
Step #3:    2963     timeout=timeout,
Step #3:    2964     restart_job_on_worker_restart=restart_job_on_worker_restart,
Step #3:    2965     enable_web_access=enable_web_access,
Step #3:    2966     tensorboard=tensorboard,
Step #3:    2967     reduction_server_container_uri=reduction_server_container_uri
Step #3:    2968     if reduction_server_replica_count > 0
Step #3:    2969     else None,
Step #3:    2970     sync=sync,
Step #3:    2971     create_request_timeout=create_request_timeout,
Step #3:    2972 )
Step #3: 
Step #3: File ~/.local/lib/python3.9/site-packages/google/cloud/aiplatform/base.py:750, in optional_sync.<locals>.optional_run_in_thread.<locals>.wrapper(*args, **kwargs)
Step #3:     748     if self:
Step #3:     749         VertexAiResourceNounWithFutureManager.wait(self)
Step #3: --> 750     return method(*args, **kwargs)
Step #3:     752 # callbacks to call within the Future (in same Thread)
Step #3:     753 internal_callbacks = []
Step #3: 
Step #3: File ~/.local/lib/python3.9/site-packages/google/cloud/aiplatform/training_jobs.py:3202, in CustomContainerTrainingJob._run(self, dataset, annotation_schema_uri, worker_pool_specs, managed_model, args, environment_variables, base_output_dir, service_account, network, bigquery_destination, training_fraction_split, validation_fraction_split, test_fraction_split, training_filter_split, validation_filter_split, test_filter_split, predefined_split_column_name, timestamp_split_column_name, timeout, restart_job_on_worker_restart, enable_web_access, tensorboard, reduction_server_container_uri, sync, create_request_timeout)
Step #3:    3183             spec["containerSpec"]["env"] = [
Step #3:    3184                 {"name": key, "value": value}
Step #3:    3185                 for key, value in environment_variables.items()
Step #3:    3186             ]
Step #3:    3188 (
Step #3:    3189     training_task_inputs,
Step #3:    3190     base_output_dir,
Step #3:    (...)
Step #3:    3199     tensorboard=tensorboard,
Step #3:    3200 )
Step #3: -> 3202 model = self._run_job(
Step #3:    3203     training_task_definition=schema.training_job.definition.custom_task,
Step #3:    3204     training_task_inputs=training_task_inputs,
Step #3:    3205     dataset=dataset,
Step #3:    3206     annotation_schema_uri=annotation_schema_uri,
Step #3:    3207     training_fraction_split=training_fraction_split,
Step #3:    3208     validation_fraction_split=validation_fraction_split,
Step #3:    3209     test_fraction_split=test_fraction_split,
Step #3:    3210     training_filter_split=training_filter_split,
Step #3:    3211     validation_filter_split=validation_filter_split,
Step #3:    3212     test_filter_split=test_filter_split,
Step #3:    3213     predefined_split_column_name=predefined_split_column_name,
Step #3:    3214     timestamp_split_column_name=timestamp_split_column_name,
Step #3:    3215     model=managed_model,
Step #3:    3216     gcs_destination_uri_prefix=base_output_dir,
Step #3:    3217     bigquery_destination=bigquery_destination,
Step #3:    3218     create_request_timeout=create_request_timeout,
Step #3:    3219 )
Step #3:    3221 return model
Step #3: 
Step #3: File ~/.local/lib/python3.9/site-packages/google/cloud/aiplatform/training_jobs.py:749, in _TrainingJob._run_job(self, training_task_definition, training_task_inputs, dataset, training_fraction_split, validation_fraction_split, test_fraction_split, training_filter_split, validation_filter_split, test_filter_split, predefined_split_column_name, timestamp_split_column_name, annotation_schema_uri, model, gcs_destination_uri_prefix, bigquery_destination, create_request_timeout)
Step #3:     738 # create training pipeline
Step #3:     739 training_pipeline = gca_training_pipeline.TrainingPipeline(
Step #3:     740     display_name=self._display_name,
Step #3:     741     training_task_definition=training_task_definition,
Step #3:    (...)
Step #3:     746     encryption_spec=self._training_encryption_spec,
Step #3:     747 )
Step #3: --> 749 training_pipeline = self.api_client.create_training_pipeline(
Step #3:     750     parent=initializer.global_config.common_location_path(
Step #3:     751         self.project, self.location
Step #3:     752     ),
Step #3:     753     training_pipeline=training_pipeline,
Step #3:     754     timeout=create_request_timeout,
Step #3:     755 )
Step #3:     757 self._gca_resource = training_pipeline
Step #3:     759 _LOGGER.info("View Training:\n%s" % self._dashboard_uri())
Step #3: 
Step #3: File ~/.local/lib/python3.9/site-packages/google/cloud/aiplatform_v1/services/pipeline_service/client.py:734, in PipelineServiceClient.create_training_pipeline(self, request, parent, training_pipeline, retry, timeout, metadata)
Step #3:     729 metadata = tuple(metadata) + (
Step #3:     730     gapic_v1.routing_header.to_grpc_metadata((("parent", request.parent),)),
Step #3:     731 )
Step #3:     733 # Send the request.
Step #3: --> 734 response = rpc(
Step #3:     735     request,
Step #3:     736     retry=retry,
Step #3:     737     timeout=timeout,
Step #3:     738     metadata=metadata,
Step #3:     739 )
Step #3:     741 # Done; return the response.
Step #3:     742 return response
Step #3: 
Step #3: File ~/.local/lib/python3.9/site-packages/google/api_core/gapic_v1/method.py:154, in _GapicCallable.__call__(self, timeout, retry, *args, **kwargs)
Step #3:     151     metadata.extend(self._metadata)
Step #3:     152     kwargs["metadata"] = metadata
Step #3: --> 154 return wrapped_func(*args, **kwargs)
Step #3: 
Step #3: File ~/.local/lib/python3.9/site-packages/google/api_core/grpc_helpers.py:59, in _wrap_unary_errors.<locals>.error_remapped_callable(*args, **kwargs)
Step #3:      57     return callable_(*args, **kwargs)
Step #3:      58 except grpc.RpcError as exc:
Step #3: ---> 59     raise exceptions.from_grpc_error(exc) from exc
Step #3: 
Step #3: InvalidArgument: 400 Unsupported service account. 1012616486416@cloudbuild.gserviceaccount.com
Step #3:

**Comment by manuelamunategui** [comment]
Regarding PR #509 (Refresh of PyTorch Image Classification Multi-Node Distributed Data), the issue seems to be around the service account allocated by the automated tester in GitHub. When running the script in Workbench, it assigns compute engine account (ex 931647533046-compute@developer.gserviceaccount.com), while the GitHub test allocates a cloud build service account (ex 1012616486416@cloudbuild.gserviceaccount.com). We are not sure how the autotest assigns accounts, but this script works in both Workbench and Colab. I'll add this to the comments in the PR.

**Review by andrewferlitsch — APPROVED** [review]

**Comment by andrewferlitsch** [comment]
still running > 1 day:
Google Cloud Build / vertex-ai-notebook-execution-test (python-docs-samples-tests)
Started 1d 5h 15m 48s ago

**Comment by kweinmeister** [comment]
Build error: needs `pip install pyarrow`

**Pull request merged**
