### PR TITLE
Added VPC network name arg

### PR DESCRIPTION
**Pull request by ivanmkc**
Ran linter and added `VPC network name` for notebook testing in preparation of https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/312.

This also fully enables private pools now that the CloudBuild bug was fixed by service team.

### CODE REVIEW

**Comment by ivanmkc** [comment]
> Build still failing with this error:
> 
> ```
> usage: execute_changed_notebooks_cli.py [-h] --test_paths_file TEST_PATHS_FILE
>                                         --container_uri CONTAINER_URI
>                                         --variable_project_id
>                                         VARIABLE_PROJECT_ID --variable_region
>                                         VARIABLE_REGION --staging_bucket
>                                         STAGING_BUCKET --artifacts_bucket
>                                         ARTIFACTS_BUCKET
>                                         [--should_parallelize [SHOULD_PARALLELIZE]]
>                                         [--base_branch BASE_BRANCH]
>                                         [--variable_vpc_network VARIABLE_VPC_NETWORK]
>                                         [--private_pool_id PRIVATE_POOL_ID]
> execute_changed_notebooks_cli.py: error: unrecognized arguments: --vpc_network_name 
> ```

That's been fixed.

**Comment by ivanmkc** [comment]
Notebook failures are the usual suspects.

**Comment by ivanmkc** [comment]
Rerunning CI due to fixed BQ issue.

**Comment by andrewferlitsch** [comment]
@ivanmkc no update since Feb 28. Is this PR obsolete?

**Comment by ivanmkc** [comment]
Closing this, will fix in https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/836

**Pull request closed without merging**
