### PR TITLE
Workaround tensorboard/GCS issue for Cloud Shell

### PR DESCRIPTION
**Pull request by vertexcite**
Without `--load_fast=false` there will be `401 Unauthorized` for GCS log loads. 
See https://github.com/tensorflow/tensorboard/issues/4784#issuecomment-868945650

### CODE REVIEW

**Comment by kweinmeister** [comment]
The linter caught a couple (previously existing) issues:
```
notebooks/official/matching_engine/two-tower-model-introduction.ipynb:cell_5:7:17: E225 missing whitespace around operator
    shell_output=hash("67d91c56")
                ^
notebooks/official/matching_engine/two-tower-model-introduction.ipynb:cell_13:1:1: F401 'json' imported but unused
import json
```

Also, a CLA is needed.

Thanks for the contribution!

**Comment by kweinmeister** [comment]
@vertexcite I have resolved the linting issues in another PR. Just need to get your CLA to approve this. You can find out more in the Details link next to the CI check for the CLA.

**Comment by andrewferlitsch** [comment]
Hum, looks like the lint warning on json was incorrect?

Step #3: Traceback (most recent call last):
Step #3:   File "/workspace/.cloud-build/execute_notebook_cli.py", line 36, in <module>
Step #3:     execute_notebook_helper.execute_notebook(
Step #3:   File "/workspace/.cloud-build/execute_notebook_helper.py", line 91, in execute_notebook
Step #3:     raise execution_exception
Step #3:   File "/workspace/.cloud-build/execute_notebook_helper.py", line 56, in execute_notebook
Step #3:     pm.execute_notebook(
Step #3:   File "/builder/home/.local/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
Step #3:     raise_for_execution_errors(nb, output_path)
Step #3:   File "/builder/home/.local/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
Step #3:     raise error
Step #3: papermill.exceptions.PapermillExecutionError: 
Step #3: ---------------------------------------------------------------------------
Step #3: Exception encountered at "In [28]":
Step #3: ---------------------------------------------------------------------------
Step #3: NameError                                 Traceback (most recent call last)
Step #3: Input In [28], in <cell line: 1>()
Step #3: ----> 1 request = json.dumps({"instances": input_items})
Step #3:       2 with open("request.json", "w") as writer:
Step #3:       3     writer.write(f"{request}\n")
Step #3: 
Step #3: NameError: name 'json' is not defined
Step #3:

**Comment by andrewferlitsch** [comment]
@vertexcite build failed:

Traceback (most recent call last):
Step #3:   File "/workspace/.cloud-build/execute_notebook_cli.py", line 36, in <module>
Step #3:     execute_notebook_helper.execute_notebook(
Step #3:   File "/workspace/.cloud-build/execute_notebook_helper.py", line 91, in execute_notebook
Step #3:     raise execution_exception
Step #3:   File "/workspace/.cloud-build/execute_notebook_helper.py", line 56, in execute_notebook
Step #3:     pm.execute_notebook(
Step #3:   File "/builder/home/.local/lib/python3.9/site-packages/papermill/execute.py", line 122, in execute_notebook
Step #3:     raise_for_execution_errors(nb, output_path)
Step #3:   File "/builder/home/.local/lib/python3.9/site-packages/papermill/execute.py", line 234, in raise_for_execution_errors
Step #3:     raise error
Step #3: papermill.exceptions.PapermillExecutionError: 
Step #3: ---------------------------------------------------------------------------
Step #3: Exception encountered at "In [28]":
Step #3: ---------------------------------------------------------------------------
Step #3: NameError                                 Traceback (most recent call last)
Step #3: Input In [28], in <cell line: 1>()
Step #3: ----> 1 request = json.dumps({"instances": input_items})
Step #3:       2 with open("request.json", "w") as writer:
Step #3:       3     writer.write(f"{request}\n")
Step #3: 
Step #3: NameError: name 'json' is not defined

**Comment by vertexcite** [comment]
> @vertexcite build failed.

@andrewferlitsch The change I've requested is not executable code, it's just in a markup cell, so it is not the cause of the failure, so I think this should just be merged, the failure would be the same before this is merged as it will be after.

**Comment by vertexcite** [comment]
> @vertexcite build failed.

@andrewferlitsch The change I've requested is not executable code, it's just in a markup cell, so it is not the cause of the failure, so I think this could just be merged, the failure would be the same before this is merged as it will be after.

Nevertheless, I've added the missing import with [42228db](https://github.com/GoogleCloudPlatform/vertex-ai-samples/pull/386/commits/42228dbb2e27982ee4d15502b6e53e3fc3fa0fb0)

**Review by kweinmeister — APPROVED** [review]

**Comment by kweinmeister** [comment]
`ResourceExhausted: 429 The following quotas are exceeded: DeployedCustomModelsPerProjectPerRegion`

**Review by kweinmeister — APPROVED** [review]

**Pull request merged**
