### PR TITLE
fix: update Tabular Forecasting prediction table

### PR DESCRIPTION
**Pull request by jwlee98**
Change bq://bigquery-public-data:iowa_liquor_sales_forecasting.2020_sales_train into bq://bigquery-public-data:iowa_liquor_sales_forecasting.2021_sales_predict for PREDICTION_DATASET_BQ_PATH

### CODE REVIEW

**Review by kweinmeister — APPROVED** [review]

**Comment by andrewferlitsch** [comment]
@jwlee98 Still same error:

 AttributeError                            Traceback (most recent call last)
Step #3: Input In [26], in <cell line: 6>()
Step #3:       5 prediction_results = list()
Step #3:       6 for blob in bp_iter_outputs:
Step #3: ----> 7     if blob.name.split("/")[-1].startswith("prediction"):
Step #3:       8         prediction_results.append(blob.name)
Step #3:      10 tags = list()
Step #3: 
Step #3: File ~/.local/lib/python3.9/site-packages/google/cloud/bigquery/table.py:1411, in Row.__getattr__(self, name)
Step #3:    1409 value = self._xxx_field_to_index.get(name)
Step #3:    1410 if value is None:
Step #3: -> 1411     raise AttributeError("no row field {!r}".format(name))
Step #3:    1412 return self._xxx_values[value]
Step #3: 
Step #3: AttributeError: no row field 'name'

**Comment by kweinmeister** [comment]
Hi, I will merge this change, and have created another [issue](https://github.com/GoogleCloudPlatform/vertex-ai-samples/issues/453) for the unrelated, pre-existing problem.

**Pull request merged**
